### ISSUE TITLE
Problem compiling react-native-google-cast

### ISSUE THREAD

**Issue by pablopi** [charliesbox/react-native-google-cast#11]
Hello,

I'm trying to compile the react-native-google-cast and when my react native application tries to do this I get: 

```
 problem occurred configuring project ':react-native-google-cast'.
   > Could not resolve all dependencies for configuration ':react-native-google-cast:_debugCompile'.
      > Could not find com.google.android.gms:play-services-cast:9.0.0.
```

Any tip?

**Comment by undef1ned** [comment]
Check this, the problem is a little bit different, but may-be it will help

https://github.com/charliesbox/react-native-google-cast/issues/6#issuecomment-235058572
