### ISSUE TITLE
npm install error: "peerinvalid Peer react-native-google-cast@1.0.0 wants react-native@^0.29.0"

### ISSUE THREAD

**Issue by hirmes** [charliesbox/react-native-google-cast#13]
When trying to install with `npm`, in a project with a recent version of React Native, I'm getting this error:
```node
npm ERR! peerinvalid Peer react-native-google-cast@1.0.0 wants react-native@^0.29.0
```

It appears that both the `master` branch and the latest `features/new-functions` branch include these outdated references:

`package.json`:

```javascript
"peerDependencies": {
    "react-native": "^0.29.0"
```

`build.gradle`:

```javascript
dependencies {
    ...
    compile 'com.facebook.react:react-native:0.20.+'
```

Can these be updated to the latest version?

**Comment by jackbillstrom** [comment]
@hirmes Have you tried? If so, what errors do you get?

**Comment by hirmes** [comment]
@jackbillstrom Updating the `package.json` reference to `"react-native": "*"` and the `build.gradle` reference to `compile 'com.facebook.react:react-native:+'` allows the package to install without npm reporting any errors. I haven't yet determined if those changes cause any issues within an RN project though.

**Comment by hirmes** [comment]
@jackbillstrom Just to follow up a bit more, I've determined that changing the `build.gradle` file is unnecessary to install without npm errors.  Just the `package.json` change is needed.

Also, I'm running npm v2.15.8, so maybe this older version is the cause of the error.

**Comment by charliesbox** [comment]
i removed the peerdependency requirement in the last version. the warning shouldn't appear again.

If so, please reopen this issue.
