### ISSUE TITLE
undefined is not an object (evaluating 'GoogleCast.DEVICE_AVAILABLE') on Android

### ISSUE THREAD

**Issue by codetony25** [charliesbox/react-native-google-cast#19]
currently getting this on version react-native-google-cast version 1.2.0, when doing `react-native run-android` 
<img width="378" alt="screen shot 2016-11-21 at 6 23 44 pm" src="https://cloud.githubusercontent.com/assets/10192761/20508620/ab874546-b017-11e6-99a8-920e3d29681b.png">

**Comment by charliesbox** [comment]
Could you try the example app? I just ran it, and I can see all the values from the Chromecast object

**Comment by codetony25** [comment]
Just did it on your provided example and getting the same for android:

<img width="474" alt="screen shot 2016-11-22 at 3 31 50 am" src="https://cloud.githubusercontent.com/assets/10192761/20522275/453b936c-b064-11e6-964f-b994cef899a4.png">

This is working on iOS by the way, since only your index.ios.js is the one containing your example component., but displays this error for Android. 

To reproduce this, I went inside your `index.android.js` and changed it to:

```js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import Main from './app/main';

class example extends Component {
  render() {
    return (
      <Main />
    );
  }
}

AppRegistry.registerComponent('example', () => example);

```

I then opened my android simulator and ran `react-native run-android` to get this error message. May I ask if this was what you had also tried but was successful? I may be missing something.

I notice that your `build.grade` in `/example/android` has the classPath of: `classpath 'com.android.tools.build:gradle:2.2.1'`

after building does your `gradle-wrapper.properties` in `example/android` look like this?

```js
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
```

I may even be wrong that it is even a gradle build problem. Let me know what you think or if you can give me some advice on the problem and I may offer some help in a pull request.

**Comment by codetony25** [comment]
Okay finally! spent the whole day figuring this out. Here's how I resolved it:

first did `react-native android` to reset my android bindings, did a `npm install` then `react-native link` to link up my dependencies.

Then, in my `android/build.gradle` updated my version to be 2.2.1:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

then in `/android/gradle/wrapper/gradle-wrapper.properties` I had the latest gradle version:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.2.1-all.zip
```

After all that, my android app finally ran and i'm able to see everything! But! i'm am getting this error tho: `Cannot invoke Chromecast.startScan();`, for now i'm just going to comment this out and figure out what's wrong. Unless you guys have any ideas

**Comment by charliesbox** [comment]
good to know!

last issue is weird. i've never received that log before. if you could share an example of your project to take a look, i can get a better idea of what is happening.

thanks for posting your research!

**Comment by swapkats** [comment]
@codetony25 Did you get to fix the `Cannot invoke Chromecast.startScan()` issue. I'm facing the same problem.

**Comment by codetony25** [comment]
Yes, I have figured this out. Although it wasn't obvious in the documentation. In your build.gradle located in `projectName/android/app/build.gradle`, You need to include the google play services for google cast in your dependencies:

```
dependencies {
    ....
    compile project(':react-native-google-cast')
    compile project(':react-native-device-info')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-cast:10.0.1" // <---- ADD THIS
}
```

You may also need to install the latest google play service sdk package as well in Android Studio SDK Manager if you are using those emulators.

**Comment by swapkats** [comment]
@codetony25 thanks a lot, this fixed my problem. Not sure what went wrong for you.

**Comment by codetony25** [comment]
@swapkats were you able to detect other chromecast devices?

**Comment by swapkats** [comment]
@codetony25 no, I don't have an actual chrome cast to detect to try this. Sorry.

**Comment by llewan** [comment]
Hi @codetony25 I'm able to detect a list of Chromecast devices thanks to this PR #27
