### ISSUE TITLE
iOS error: GoogleCast/GoogleCast.h file not found

### ISSUE THREAD

**Issue by peggyrayzis** [charliesbox/react-native-google-cast#21]
Currently running React Native v0.38. We also noticed that this error was happening with 0.35.

After linking and rerunning the build for iOS in Xcode, we receive an error message that GoogleCast/GoogleCast.h file is not found. We have installed the google-cast-sdk Pod from Cocoapods & added it to our Podfile as described in the readme. We are running the build from the workspace created by Cocoapods. Any help with this issue would be greatly appreciated, we're really excited to try out your module and thought your Medium post describing it was awesome!

cc @kkemple

<img width="1407" alt="googlecast_h_and_kkemple_mls-work-laptop-kkemple____documents_projects_mls_bulbasaur" src="https://cloud.githubusercontent.com/assets/18017067/20762017/ec38860e-b6f2-11e6-8243-be803f65cd41.png">

**Comment by charliesbox** [comment]
@peggyrayzis sorry for the delay, i had a lot of work to do lately :)

I just saw that you already closed the issue. That means that you found a solution for this problem?

Let me know, to help you if you need it.

- Charlie

**Comment by peggyrayzis** [comment]
Hi Charlie! Thanks for following up. To fix the issue, we just copied & pasted your GoogleCast.h/m files into our project. I think it might have something to do with using Swift & not linking our frameworks properly. 🤔 I'm pretty new to native development though so not 100% sure.

**Comment by charliesbox** [comment]
Mmm, this is weird, first I thought that the linking process didn't happen, but if after pasting the files worked, it looks like a different issue.

I'm curious about the use of swift. Are you integrating react native to an existing native project?

**Comment by peggyrayzis** [comment]
Nope, this is a project that was started in React Native. We do use Swift for a couple native components that we bridge over to JS.

The only difference we could find between our project & your example is here:
https://github.com/charliesbox/react-native-google-cast/blob/master/example/ios/Podfile#L5-L6

We have that line uncommented because of our Swift code. We tried linking the GoogleCast framework manually to our project but for some reason, it still couldn't find the header file.

**Comment by charliesbox** [comment]
I added a configuration in the library to search the cocoapods files. Will try the example uncommenting the line just to discard this option.

**Comment by undef1ned** [comment]
Having exact the same issue 
@peggyrayzis could you please point where should I put the h/m files to make it work? Thanks

**Comment by charliesbox** [comment]
@undef1ned you can add it inside your current project. Xcode manages the files in a logic way, so the important thing is just to drag them inside it.

After that, they will become part of your current libraries.

First version of this library worked in that way. You can check the instructions for that approach here [link](https://github.com/charliesbox/react-native-google-cast/blob/e37675843e076df7a4c2cfcb942f25809424074f/README.md)

Will take a further look as soon I have some free time.

**Comment by LeonidasEsteban** [comment]
I have the same issue :(

**Comment by charliesbox** [comment]
@LeonidasEsteban could you try with this PR? https://github.com/charliesbox/react-native-google-cast/pull/42

**Comment by developersoul** [comment]
Another solution is move the GoogleCast.framework headers into to Pods/Headers/Public/google-cast-sdk/GoogleCast

**Comment by mtkopone** [comment]
Here's how to fix it:


In the xcode project navigator, open Libraries/GoogleCase.xcodeproj
Choose the GoogleCast target, and Build Settings
Add the following to "Framework Search Paths": $(PROJECT_DIR)/../../../ios/Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release
