### ISSUE TITLE
How can I cast a specific app, with a specific appId ?

### ISSUE THREAD

**Issue by samuelbriole** [charliesbox/react-native-google-cast#25]
I made a custom receiver app, and I would like to load it on my Audio Chromecast from my RN app.
How could I do that ?

**Comment by charliesbox** [comment]
It's not supported right now. 

I don't have enough time to work on that right now, but feel free to open a PR to add the functionality :) !

**Comment by samuelbriole** [comment]
Alright ! 
I'm going to investigate :)

**Comment by Rogergonzalez21** [comment]
+1 on this functionality!

**Comment by charliesbox** [comment]
Fixed by https://github.com/charliesbox/react-native-google-cast/pull/29 :)

**Comment by samuelbriole** [comment]
@charliesbox Thank you ❤️
