### ISSUE TITLE
Does this work in the emulator?

### ISSUE THREAD

**Issue by masterwok** [charliesbox/react-native-google-cast#37]
Hey,

Are there any known issues getting this to run properly in the Android emulator?

The problem that I'm seeing is that "ChromeCast.DEVICE_AVAILABLE" event doesn't seem to be emitted, as my callback is never executed.

On the emulator I'm able to hit my router by IP, so I would think that it would find devices. However, I'm not able to see if it's the emulator because I don't own an Android device.

Here's the code I have:

```
import React, {Component} from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    DeviceEventEmitter
} from 'react-native';

import Chromecast from 'react-native-google-cast';


DeviceEventEmitter.addListener(Chromecast.DEVICE_AVAILABLE, () => {
    console.log('hit'); // *** This is not being called ***
});

Chromecast.startScan();
console.log('starting scan');
```

Thanks!

**Comment by charliesbox** [comment]
yup! looks like this is linked to an issue that happened lately. Working on that right now on this PR https://github.com/charliesbox/react-native-google-cast/pull/40

**Comment by masterwok** [comment]
Awesome, thanks!
