### ISSUE TITLE
Does have support for Styled Media Receivers.

### ISSUE THREAD

**Issue by maximmcnair** [charliesbox/react-native-google-cast#48]
https://developers.google.com/cast/docs/styled_receiver

**Comment by charliesbox** [comment]
@maximmcnair not yet, but PRs are welcome :) !

**Comment by Diskiddin** [comment]
I believe it does because the app supports custom app id's correct? I use a custom receiver registered through the google cast development console and it works fine, and the styled media receiver is used the same way.

**Comment by maximmcnair** [comment]
I does work by passing in our app id here: `Chromecast.startScan(APP_ID);`. But only when using the git repo, the package on npm is not up to date.

**Comment by ramubhai** [comment]
Any guideline, when can we expect it to be updated on NPM?
