### ISSUE TITLE
Support RNPM

### ISSUE THREAD

**Issue by charliesbox** [charliesbox/react-native-google-cast#5]

**Comment by jsdario** [comment]
Seems to work with Android, but I still have to manually build it on iOS. Am I wrong?

**Comment by charliesbox** [comment]
well, you don't need to build it as a separate entity. You just add the folder to xcode, and add cocoapods to support the native sdk.

will look further to add the library without effort thru rnpm. just need to find some free time.

**Comment by charliesbox** [comment]
Heads Up to this issue: I'm working on supporting react-native link !

It's almost done. Should be ready this week.

**Comment by charliesbox** [comment]
`react-native link react-native-google-cast` will do the trick for both platforms!

 Cocoapods is still required to manage the sdk, as it is kinda huge to upload it into the repository
