### ISSUE TITLE
Build fails on Android due to conflict with other module

### ISSUE THREAD

**Issue by undef1ned** [charliesbox/react-native-google-cast#6]
I've tried to build the app with this library but it fails, I found the reason is that I'm also using https://github.com/zo0r/react-native-push-notification which has gms dependancy

> * What went wrong:
> Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> > java.util.zip.ZipException: duplicate entry: com/google/android/gms/iid/zzb$zza.class

I'm on LG G4 / Android 5.1 / RN 0.26.3

**Comment by charliesbox** [comment]
have you enabled multidex in your app?

**Comment by undef1ned** [comment]
Yes, in my main project I have multiDexEnabled true

**Comment by charliesbox** [comment]
Try adding dexOptions

Problem I found with other google libraries is that they include all the play services package, when you only require just some of the services.

If this doesn't work, last step would be to check the play services config.

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    dexOptions {
        javaMaxHeapSize "2g"
    }

    defaultConfig {
        ...
   }
```

**Comment by charliesbox** [comment]
BTW, this is my build.gradle config. Im using this library and google-signin

For the record, i'm not adding `apply plugin [...]` at the end of the file

```
 compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-auth:9.2.0'
    compile 'com.google.android.gms:play-services-cast:9.2.0'
```

**Comment by undef1ned** [comment]
Sorry for the late reply,

I just noticed that this module generates gms aars@9.0.0 while notification module depends on

```
compile 'com.google.android.gms:play-services-gcm:7.8.0'
```

adding this line to main project build.gradle

```
    compile ('com.google.android.gms:play-services-gcm:9.0.0') {
        force = true;
    }
```

fixed my issue

**Comment by charliesbox** [comment]
oh, a difference between services versions. great you found a solution! will close the issue then :)
