### ISSUE TITLE
[Android] 0 Devices

### ISSUE THREAD

**Issue by jalbrecht** [charliesbox/react-native-google-cast#7]
I'm getting the right devices on the iOS end, just not Android. They share the same class for both so I don't think its on my end. I'm listening to the DEVICE_AVAILABLE event then calling getDevices() right after and I'm getting the "devices size 0" log. 

I tried polling every few seconds regardless of the event and still nothing.

I see the chromecast device when I open the Chromecast app, and I can see it from the iOS device immediately before/after I test on Android. Also double checked that I'm on the same network.

Snippet of my RN code:

```
    async function getDevices() {
      let devices = await Chromecast.getDevices();

      console.log('[GoogleCastModule] New Devices', devices);
      
      myThis.chromecasts = devices;
      myThis.sendUpdatedList();
    }

    // Available Device
    DeviceEventEmitter.addListener(Chromecast.DEVICE_AVAILABLE, function(data) {
      getDevices();
    });
```

I see 0 devices on the java log so I don't think this snippet is very helpful

**Comment by charliesbox** [comment]
hi, i just tried your example, and it worked fine for me.

Did you add  `Chromecast.startScan();` method?

```
componentDidMount() {
    Chromecast.startScan();
    DeviceEventEmitter.addListener(Chromecast.DEVICE_AVAILABLE, (existance) => this.getDevices());
    DeviceEventEmitter.addListener(Chromecast.MEDIA_LOADED, () => {
    });
    DeviceEventEmitter.addListener(Chromecast.DEVICE_CONNECTED, () => {
      this.chromecastCastMedia()
    });
  }

  async getDevices() {
    let devices = await Chromecast.getDevices();
    console.log('[GoogleCastModule] New Devices', devices);
  }

**Comment by jalbrecht** [comment]
Yup. Here is the log:

```
adb logcat | grep "GoogleCastModule"
07-14 15:40:12.142 11619 11653 E GoogleCastModule: start scan Chromecast 
07-14 15:40:12.202 11619 11619 E GoogleCastModule: Chromecast Initialized for the first time!
07-14 15:40:12.722 11619 11619 E GoogleCastModule: onCastAvailabilityChanged: exists? true
07-14 15:40:12.722 11619 11653 E GoogleCastModule: devices size 0
07-14 15:40:12.722 11619 11652 I ReactNativeJS: '[GoogleCastModule] New Devices', []
```

Do you happen to have a skeleton app I can run/compare to? I'm going to try on a fresh RN build now. Maybe something is conflicting

**Comment by jalbrecht** [comment]
Going to close this. Looks like its (still) an issue on the CCL/Google Cast SDK end.

Had the same results on the example app until I rebooted the Chromecast itself then it appeared. Repeated on 2 devices.

More info if you're interested:
https://github.com/googlecast/CastCompanionLibrary-android/issues/36
https://code.google.com/p/google-cast-sdk/issues/detail?id=314

I'll make a PR if there's a code fix

**Comment by charliesbox** [comment]
Thanks for the conclusion @jalbrecht. Waiting for that PR!
