### ISSUE TITLE
Build Fails - No Delegate set : lost message:Done

### ISSUE THREAD

**Issue by mfs780** [charliesbox/react-native-google-cast#8]
I am getting the following error when trying to build after following the instructions. Same errors occur when I try using the example application.

I get a long list of errors some of which are the following. Let me know if you can help. Thanks.

AAPT out(1063813574) : No Delegate set : lost message:Done
AAPT: C:\Users\mfs78\Desktop\reactnative\CastHelloText-chrome-master\example\node_modules\react-native-google-cast\android\build\intermediates\exploded-aar\com.google.android.libraries.cast.companionlibrary\ccl\2.8.4\res\drawable-xhdpi-v11\ic_stat_action_democast.png ERROR: Unable to open PNG file

**Comment by charliesbox** [comment]
is the issue still happening to you?

**Comment by charliesbox** [comment]
inactive issue. closing.

**Comment by thewikus** [comment]
I still get this issue, it seems like it only happens on our CI server.
