### ISSUE TITLE
undefined is not an object (evaluating 'GoogleCast.DEVICE_CHANGED')

### ISSUE THREAD

**Issue by chiraggshah** [charliesbox/react-native-google-cast#9]
I get the following error. I have tested on simulator and on device.

```
undefined is not an object (evaluating 'GoogleCast.DEVICE_CHANGED')

<unknown>
    GoogleCast.js:36
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    index.ios.js:16
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:58
_require
    require.js:49
global code
    require-0.js:1
```

**Comment by charliesbox** [comment]
@chiraggshah are you having this issue in both platforms?

**Comment by chiraggshah** [comment]
@charliesbox : I had tried only for iOS. I tried your sample app and that worked perfectly. 

On a sidenote, what if I want to cast a URL which is not a media, maybe a webpage or a slideshow of images? Is that possible? If not, should I create a separate issue for it?

**Comment by charliesbox** [comment]
both are possible, but it requires a custom receiver. I think it could be simple enough, so if anybody feels in the mood, it could open a pull request to add the feature.

Feel free to open the issue :)

**Comment by jsdario** [comment]
@chiraggshah did you solve it? I believe it is because we need to properly link the libraries before.

**Comment by chiraggshah** [comment]
@jsdario : I didnt try it later. I tried out the sample app and that worked out for me.

**Comment by charliesbox** [comment]
@jsdario did you link the library ? According the readme:

- In Libraries choose Add files... and add the folder ios/RNGoogleCast from the node_modules/react-native-google-cast/ios folder. Be sure that the option copy if needed is unchecked.
- Add pod 'google-cast-sdk' to your Podfile. This is the easier way to have the sdk up to date.
- If you get an error after building the project, be sure that $(inherited) was added to Other Linker Flags in Build Settings

**Comment by jsdario** [comment]
Hi @charliesbox thanks for replying. Yes I followed all those steps but I was not able to link it correctly. React Native Packager returned `Skipping RNGoogleCast, file of type directory unexpected`. So I understand that did not help.

If there is a way to implement this as `rnpm` plugin I can make a PR or something. But I yet do not know fully how to do this.

**Comment by charliesbox** [comment]
I haven't read the rnpm documentations yet, so I can't guide you there.
So, this happens to you in debug mode?

**Comment by vindvaki** [comment]
@jsdario I just ran into the same issue, and found that I had to add them as "group" as opposed to "folder" and now 
```javascript
import Chromecast from 'react-native-google-cast';
```
works for me.

**Comment by charliesbox** [comment]
@vindvaki good tip. Will update the readme to include this. Thanks!

**Comment by charliesbox** [comment]
I just published a new version of the library, supporting `react-native link`. As this issue looks to be related to the way it was linked manually, this version should fix this problem.

Let me know if you still are having this issue :)

**Comment by charliesbox** [comment]
DEVICE_CHANGED was removed in the last version. Please use DEVICE_CONNECTED and DEVICE_DISCONNECTED to detect changes in the devices.
